export const Images = {
  addaddress: import.meta.env.BASE_URL + "img/addaddress.png",
  addressdetails: import.meta.env.BASE_URL + "img/addressdetails.png",
  auth: import.meta.env.BASE_URL + "img/auth.png",
  banner: import.meta.env.BASE_URL + "img/banner.png",
  brands: import.meta.env.BASE_URL + "img/brands.png",
  cart: import.meta.env.BASE_URL + "img/cart.png",
  categories: import.meta.env.BASE_URL + "img/categories.png",
  contactus: import.meta.env.BASE_URL + "img/contactus.png",
  downloadapk: import.meta.env.BASE_URL + "img/downloadapk.png",
  features: import.meta.env.BASE_URL + "img/features.png",
  footer: import.meta.env.BASE_URL + "img/footer.png",
  homepage: import.meta.env.BASE_URL + "img/homepage.png",
  incredibleoffers: import.meta.env.BASE_URL + "img/incredibleoffers.png",
  logout: import.meta.env.BASE_URL + "img/logout.png",
  mostsolf: import.meta.env.BASE_URL + "img/mostsolf.png",
  myorder: import.meta.env.BASE_URL + "img/myorder.png",
  myprofile: import.meta.env.BASE_URL + "img/myprofile.png",
  notification: import.meta.env.BASE_URL + "img/notification.png",
  paymentprofile: import.meta.env.BASE_URL + "img/paymentprofile.png",
  profile: import.meta.env.BASE_URL + "img/profile.png",
  profiledeatilsorder: import.meta.env.BASE_URL + "img/profiledeatilsorder.png",
  recommendedproducts: import.meta.env.BASE_URL + "img/recommendedproducts.png",
  search: import.meta.env.BASE_URL + "img/search.png",
  setting: import.meta.env.BASE_URL + "img/setting.png",
  singlepage: import.meta.env.BASE_URL + "img/singlepage.png",
  specification: import.meta.env.BASE_URL + "img/specification.png",
};
